name: MikoBtn-DailyBuild

on: 
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install Dependencies
      run: yarn
    - name: Generate Static Site
      run: yarn build

    - name: Deploy
      working-directory: dist
      run: |
        git config --global user.email "admin@blw.moe"
        git config --global user.name "paizi"
        git remote set-url origin https://github.com/paizi/debug.sakuramiko.org.git
        git init
        git add --all
        git commit -m "Deploy from GitHub: $GITHUB_SHA"
        git push -u --force https://${{ secrets.USERNAME }}:${{ secrets.PASSWORD }}@github.com/paizi/debug.sakuramiko.org.git master:master
